# Configuring the container

version: "1.0"

services:
  sfa-api:
    ports:
      - 5000:5000 #redirect port 5000 from my pc to port 5000 of the container
    build:
      context: ./ #it will build it using the actual context

# API CONTAINER:
# Command: docker compose up => Creates a container and adds the codes (when an image hasn't been created)
# Command: docker compose build => Creates an image (this will not run the container
# Command: ctrl C = stop no container

# docker compose up -d   ====>>> makes it keep running


